title: "Zahida Meherunnessa"
email: numi.z.nessa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  জাহিদা মেহেরুন্নেসসার কবিতার খাতা 
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://zahida-meherunnessa.github.io/" 
twitter_username: Zahida
github_username: zahida-meherunnessa

social_image: "./assets/img/zahida.logo.jpg"
social_image_alt: # Alt text for the link preview image
google_analytics_measurement_id: # G-XXXXXXXXXX

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
